package org.tests.model;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 * Application information holder
 * <p>
 * Created by ABEL.SALGADOROMERO on 15/07/2016.
 */
public class AppData {

    private String appId;
    // generated by BOX
    private String publicKeyId;
    private String clientId;
    private String secret;

    private File privateKey;
    private String privateKeyPassword;


    /**
     * Returns the private key value as a String.
     */
    public String getPrivateKey() {
        if (privateKey == null)
            return null;

        if (!privateKey.exists()) {
            // wrapping checked exception
            throw new RuntimeException(new FileNotFoundException("PrivateKey file not found: " + privateKey.getPath()));
        } else {
            try {
                return new String(Files.readAllBytes(Paths.get((privateKey).getAbsolutePath())));
            } catch (IOException e) {
                // wrapping checked exception
                throw new RuntimeException(e);
            }
        }
    }

    /**
     * Sets the private key location information.
     * Note the attribute is lazily resolved.
     *
     * @param privateKey File containing the key
     */
    public void setPrivateKey(File privateKey) {
        this.privateKey = privateKey;
    }

    /**
     * Sets the private key location information.
     * Note the attribute is lazily resolved.
     *
     * @param privateKeyPath File path containing the key
     */
    public void setPrivateKey(String privateKeyPath) {
        this.privateKey = new File(privateKeyPath);
    }

    public String getPrivateKeyPassword() {
        return privateKeyPassword;
    }

    public void setPrivateKeyPassword(String privateKeyPassword) {
        this.privateKeyPassword = privateKeyPassword;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getPublicKeyId() {
        return publicKeyId;
    }

    public void setPublicKeyId(String publicKeyId) {
        this.publicKeyId = publicKeyId;
    }

    public String getSecret() {
        return secret;
    }

    public void setSecret(String secret) {
        this.secret = secret;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }
}
